---
- name : Add 2 ESXi Host
  hosts: localhost
 
  tasks:
  - name: Add First ESXi Host to vCenter
    vmware_host:
      datacenter_name: Bicat.serhat
      cluster_name: Bicat.serhat.Cluster
      esxi_hostname: '{{ esxi_hostname1 }}'
      esxi_username: '{{ esxi_username1 }}'
      esxi_password: '{{ esxi_password1 }}'
      state: present
      
  - name: Add Second ESXi Host to vCenter
    vmware_host:
      datacenter_name: Bicat.serhat
      cluster_name: Bicat.serhat.Cluster
      esxi_hostname: '{{ esxi_hostname2 }}'
      esxi_username: '{{ esxi_username2 }}'
      esxi_password: '{{ esxi_password2 }}'
      state: present
 #    delegate_to: localhost
