- name: Add Virtual Machine to ESXi
  hosts: localhost
  
  tasks:
  - name: Add the VM to ESXi
    vmware_guest:
      datacenter: Bicat.serhat
      folder: /vm/
      esxi_hostname: "{{ esxi_hostname }}"
      name: BicatSerhat
      state: poweredon
      guest_id: debian8_64Guest
      disk:
      - size_gb: 5
        type: thin
        datastore: datastore1
      hardware:
        num_cpus: 1
        num_cpu_cores_per_socket: 1
        memory_mb: 512
