- name: Add Virtual Machine to ESXi
  hosts: localhost
  
  tasks:
  - name: Add the VM to ESXi
    vmware_guest:
      datacenter: "{{ dc_name }}"
      folder: /
      esxi_hostname: "{{ esxi_hostname }}"
      name: "{{ virtual_machine_name }}"
      state: poweredon
      guest_id: debian6_64Guest
      disk:
      - size_gb: 5
        type: thin
        datastore: datastore1
      hardware:
        num_cpus: 1
        num_cpu_cores_per_socket: 1
        memory_mb: 256
        scsi: paravirtual
      networks:
      - name: LAN 1234
        device_type: e1000
