---
- name : Create vSphere Cluster
  hosts: localhost
  
  tasks:
  - name: Create Cluster Task
    local_action:
      module: vmware_cluster
      datacenter_name: datacenter
      cluster_name: ClusterAnsible
      enable_ha: no
      enable_drs: no
      enable_vsan: no
#    delegate_to: localhost
#    register: vmfacts
