---
- name : Create vSphere Datacenter
  hosts: localhost

  tasks:
  - name: Create Datacenter Task
    local_action:
      module: vmware_datacenter
      datacenter_name: 'Bicat.serhat'
      state: present
      
#    delegate_to: localhost
#    register: vmfacts
